// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Maintainer Chen Ke",
            "url": "https://danxi.fduhole.com/about",
            "email": "dev@danta.tech"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.Info"
                        }
                    }
                }
            }
        },
        "/debug/register": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "register with email, password, not need verification code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "register, debug only",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "用户已注册",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/debug/register/_batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "register with email, password, not need verification code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "register in batch, debug only",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.RegisterInBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "用户已注册",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login with email and password, return jwt token, not need jwt",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "Logout, clear jwt credential and return successful message, logout, jwt needed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Refresh jwt token with refresh token in header, login required",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Refresh jwt token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "put": {
                "description": "reset password, reset jwt credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "验证码错误",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "register with email, password and verification code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "register",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "验证码错误、用户已注册",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/register/_webvpn": {
            "patch": {
                "description": "reset password, reset jwt credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "验证码错误",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/register/questions": {
            "get": {
                "description": "Retrieve questions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Retrieve questions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "version",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.QuestionConfig"
                        }
                    }
                }
            }
        },
        "/register/questions/_answer": {
            "post": {
                "description": "Answer questions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Answer questions",
                "parameters": [
                    {
                        "description": "answers",
                        "name": "answers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.SubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "answer correct or not",
                        "schema": {
                            "$ref": "#/definitions/apis.SubmitResponse"
                        }
                    },
                    "400": {
                        "description": "already answered, or bad request",
                        "schema": {
                            "$ref": "#/definitions/common.HttpError"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.HttpError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register/questions/_reload": {
            "post": {
                "description": "Reload questions, admin only",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Reload questions",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.HttpError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shamir": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "list related shamir PGP messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "recipient uid",
                        "name": "identity_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apis.PGPMessageResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/decrypt": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "upload shares of one user",
                "parameters": [
                    {
                        "description": "shares",
                        "name": "shares",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UploadShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.MessageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apis.IdentityNameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/decrypt/status/{user_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "get decrypt status by userID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.ShamirUserSharesResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/decrypt/{user_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "get decrypted email of one user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.DecryptedUserEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/key": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "upload all PGP PublicKeys for encryption, admin only",
                "parameters": [
                    {
                        "description": "public keys",
                        "name": "public_keys",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UploadPublicKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/common.MessageResponse"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "data": {
                                                "$ref": "#/definitions/apis.IdentityNameResponse"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/refresh": {
            "put": {
                "tags": [
                    "shamir"
                ],
                "summary": "trigger for refresh uploaded shares",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/refresh/_webvpn": {
            "patch": {
                "tags": [
                    "shamir"
                ],
                "summary": "trigger for refresh uploaded shares",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/shares": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "upload all shares of all users, cached",
                "parameters": [
                    {
                        "description": "shares",
                        "name": "shares",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UploadSharesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.MessageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apis.IdentityNameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.MessageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apis.IdentityNameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "get shamir info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.ShamirStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "trigger for updating shamir",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/shamir/{user_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shamir"
                ],
                "summary": "get shamir PGP message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "identity_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.PGPMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "list all users, admin only, not implemented",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "list all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "403": {
                        "description": "不是管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/users/admin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "list admins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "description": "get user by verifying user token or header",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete user and related jwt credentials",
                "tags": [
                    "account"
                ],
                "summary": "delete user",
                "parameters": [
                    {
                        "description": "email, password",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "密码错误",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "description": "delete user and related jwt credentials",
                "tags": [
                    "account"
                ],
                "summary": "delete user by id, admin only",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "description": "get user by id in path, owner or admin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "403": {
                        "description": "不是该用户或管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "modify user, owner or admin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "modify user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "403": {
                        "description": "不是管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/_webvpn": {
            "patch": {
                "description": "modify user, owner or admin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "modify user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "403": {
                        "description": "不是管理员",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/verify/apikey": {
            "get": {
                "description": "verify with email in query, return verification code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "verify with email in query and apikey",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "name": "apikey",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "if true, return whether registered",
                        "name": "check_register",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "email in email blacklist",
                        "name": "email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户未注册",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "apikey不正确",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "409": {
                        "description": "用户已注册",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/verify/email": {
            "get": {
                "description": "verify with email in query, Send verification email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "verify with email in query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "scope",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "check",
                        "name": "check",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.EmailVerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        },
        "/verify/email/{email}": {
            "get": {
                "description": "verify with email in path, send verification email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "verify with email in path",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "scope",
                        "name": "scope",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.EmailVerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.MessageResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apis.ApikeyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "registered": {
                    "type": "boolean"
                },
                "scope": {
                    "type": "string",
                    "enum": [
                        "register",
                        "reset"
                    ]
                }
            }
        },
        "apis.DecryptedUserEmailResponse": {
            "type": "object",
            "required": [
                "user_email"
            ],
            "properties": {
                "identity_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "apis.EmailVerifyResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "registered": {
                    "type": "boolean"
                },
                "scope": {
                    "type": "string",
                    "enum": [
                        "register",
                        "reset"
                    ]
                }
            }
        },
        "apis.IdentityNameResponse": {
            "type": "object",
            "properties": {
                "identity_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "apis.Info": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "homepage": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.LoginRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "email": {
                    "description": "email in email blacklist",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "apis.PGPMessageResponse": {
            "type": "object",
            "properties": {
                "pgp_message": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "apis.Question": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "analysis": {
                    "description": "题目解析，预留，可选",
                    "type": "string"
                },
                "answer": {
                    "description": "答案索引，单选、判断、多选，从 0 开始",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "group": {
                    "description": "题目分组，可选或必选",
                    "type": "string",
                    "enum": [
                        "optional",
                        "required",
                        "campus"
                    ]
                },
                "id": {
                    "description": "题目 ID，题库解析时自动生成，题库中不必填写，发送给客户端时必须包含",
                    "type": "integer"
                },
                "option": {
                    "description": "椰树 swift",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "options": {
                    "description": "选项描述，单选、判断、多选\n有一个或多个选项，如果是判断题，则选项只能是 true 或者 false\n如果 Answer 中的答案不在 Options 中，则会在解析时加到 Options 中",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question": {
                    "description": "问题描述",
                    "type": "string"
                },
                "type": {
                    "description": "题目类型，单选、判断、多选",
                    "enum": [
                        "single-selection",
                        "true-or-false",
                        "multi-selection"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/apis.QuestionType"
                        }
                    ]
                }
            }
        },
        "apis.QuestionConfig": {
            "type": "object",
            "required": [
                "version"
            ],
            "properties": {
                "questions": {
                    "description": "题目列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apis.Question"
                    }
                },
                "spec": {
                    "description": "出题规格",
                    "allOf": [
                        {
                            "$ref": "#/definitions/apis.QuestionSpec"
                        }
                    ]
                },
                "version": {
                    "description": "表示题库的版本号，用于判题时判断对应的题库，保障题库的平滑更新，必须填写",
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "apis.QuestionSpec": {
            "type": "object",
            "properties": {
                "in_order": {
                    "description": "表示是否由题目声明顺序由上到下顺序出题，默认为 false，即乱序出题",
                    "type": "boolean"
                },
                "number_of_campus_questions": {
                    "description": "校园题的数量\n其余规则同可选题",
                    "type": "integer"
                },
                "number_of_optional_questions": {
                    "description": "可选题的题目数量\n发送题目时，题库中的必做题都会发送，可选题会根据题目数量随机发送\n如果可选题的题目数量大于题库中的可选题数量，将会在解析时返回错误\n如果设置为 0 或者不设置，可选题不会发送\n如果设置为 -1，则题库中的可选题都会发送",
                    "type": "integer"
                },
                "number_of_questions": {
                    "description": "总题目数量\nDeprecated",
                    "type": "integer"
                }
            }
        },
        "apis.QuestionType": {
            "type": "string",
            "enum": [
                "single-selection",
                "true-or-false",
                "multi-selection"
            ],
            "x-enum-varnames": [
                "SingleSelection",
                "TrueOrFalse",
                "MultiSelection"
            ]
        },
        "apis.RegisterInBatchRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apis.LoginRequest"
                    }
                }
            }
        },
        "apis.RegisterRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "email": {
                    "description": "email in email blacklist",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "verification": {
                    "type": "string"
                }
            }
        },
        "apis.ShamirStatusResponse": {
            "type": "object",
            "properties": {
                "current_public_keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ShamirPublicKey"
                    }
                },
                "fail_message": {
                    "type": "string"
                },
                "new_public_keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ShamirPublicKey"
                    }
                },
                "now_user_id": {
                    "type": "integer"
                },
                "shamir_update_ready": {
                    "type": "boolean"
                },
                "shamir_updating": {
                    "type": "boolean"
                },
                "uploaded_shares_identity_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "warning_message": {
                    "type": "string"
                }
            }
        },
        "apis.ShamirUserSharesResponse": {
            "type": "object",
            "properties": {
                "shamir_upload_ready": {
                    "type": "boolean"
                },
                "uploaded_shares_identity_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "apis.SubmitAnswer": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "answer": {
                    "description": "答案描述，单选、判断、多选",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "题目 ID，用于判题，必须填写",
                    "type": "integer"
                }
            }
        },
        "apis.SubmitRequest": {
            "type": "object",
            "required": [
                "answers"
            ],
            "properties": {
                "answers": {
                    "description": "答案列表",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/apis.SubmitAnswer"
                    }
                },
                "version": {
                    "description": "表示题库的版本号，如果不填会使用最新的版本号判题，建议填写",
                    "type": "integer"
                }
            }
        },
        "apis.SubmitResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                },
                "correct": {
                    "description": "表示是否正确",
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "refresh": {
                    "type": "string"
                },
                "wrong_question_ids": {
                    "description": "如果提交的答案不正确，返回错误的题目 ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "apis.TokenResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "refresh": {
                    "type": "string"
                }
            }
        },
        "apis.UploadPublicKeyRequest": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "description": "all standalone public keys",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "apis.UploadShareRequest": {
            "type": "object",
            "required": [
                "identity_name"
            ],
            "properties": {
                "identity_name": {
                    "type": "string"
                },
                "share": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "apis.UploadSharesRequest": {
            "type": "object",
            "required": [
                "identity_name"
            ],
            "properties": {
                "identity_name": {
                    "type": "string"
                },
                "shares": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apis.UserShare"
                    }
                }
            }
        },
        "apis.UserShare": {
            "type": "object",
            "properties": {
                "share": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "common.ErrorDetailElement": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "param": {
                    "type": "string"
                },
                "struct_field": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "common.HttpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.ErrorDetailElement"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "common.MessageResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ShamirPublicKey": {
            "type": "object",
            "properties": {
                "armored_public_key": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "identity_name": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "has_answered_questions": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "is_shamir_admin": {
                    "type": "boolean"
                },
                "joined_time": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Open Tree Hole Auth",
	Description:      "Next Generation of Auth microservice integrated with kong for registration and issuing tokens",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
